owncloud/docs-client-android

- modules/ROOT/pages/appendices/release_notes.adoc
- modules/ROOT/pages/appendices/troubleshooting.adoc
> [2.18] [PR 1] Add missing page aliases

- antora.yml
Fixing a namy typo in antora.yml
Backport to 2.18
> Name typo fix

- antora.yml
> [2.18] [PR 3] Name typo fix

- bin/makepdf
- lib/extensions/remote-include-processor.js
- site.yml
> [2.18] [PR 11] Prepare the repo to include external adoc files

- modules/ROOT/pages/accounts.adoc
- modules/ROOT/pages/connecting.adoc
- modules/ROOT/pages/files.adoc
- modules/ROOT/pages/installation.adoc
This PR fixes broken anchors...
Backport to 2.18
> Fixing broken anchors (in- and inter-document references)

- modules/ROOT/pages/accounts.adoc
- modules/ROOT/pages/connecting.adoc
- modules/ROOT/pages/files.adoc
- modules/ROOT/pages/installation.adoc
> [2.18] [PR 13] Fixing broken anchors (in- and inter-document references)

- site.yml
New Android version (2.19)
Backport to 2.19
> New Android version

- site.yml
> [2.19] [PR 15] New Android version

- antora.yml
Version correction in antora.yml -> 2.19
No backport
> antora.yml fix for 2.19

- .drone.star
> [2.19] [PR 21] Fix drone.star for master and 2.19

- docs/new-version-branch.md
This is just a text addon to the branching documentation to be inline with docs.
* Adds a PR text proposal
* Text fixes
Backport to 2.18 and 2.19
> Update new version branch text (add PR text suggestion)

- docs/new-version-branch.md
> [2.18] [PR 25] Update new version branch text (add PR text suggestion)

- docs/new-version-branch.md
> [2.19] [PR 25] Update new version branch text (add PR text suggestion)

- bin/makepdf
> [2.18] [PR 34] Fix for makepdf refs #31

- bin/makepdf
> [2.19] [PR 34] Fix for makepdf refs #31

- README.md
- docs/new-version-branch.md
These are just minor repo text fixes outside antora.
Backport to 2.18 and 2.19
> Minor text fixes

- README.md
- docs/new-version-branch.md
> [2.18] [PR 40] Minor text fixes

- README.md
- docs/new-version-branch.md
> [2.19] [PR 40] Minor text fixes

- README.md
- package.json
- yarn.lock
> [2.18][PR 43] Add Antora Site Structure Description for Docs

- README.md
- package.json
- yarn.lock
> [2.19] [PR 43] Add Antora Site Structure Description for Docs

- package.json
Minor typo fix
Backport to 2.19 and 2.18
> typo fix caused by copy and paste

- package.json
> [2.19] [PR 46] typo fix caused by copy and paste

- package.json
> [2.18] [PR 46] typo fix caused by copy and paste

- site.yml
> [2.19] [PR 49] site.yml attribute fix

- site.yml
> [2.18] [PR 49] site.yml attribute fix

- .drone.star
- .prettierrc
- generator/generate-site.js
- package.json
- yarn.lock
References: https://github.com/owncloud/docs/pull/4633 (fix: fix elastic index handling)
Backport to 2.18 and 2.19
> Updates deployment files to be in sync with docs.

- .drone.star
- .prettierrc
- generator/generate-site.js
- package.json
- yarn.lock
> [2.18] [PR 52] Updates deployment files to be in sync with docs.

- .drone.star
- .prettierrc
- generator/generate-site.js
- package.json
- yarn.lock
> [2.19] [PR 52] Updates deployment files to be in sync with docs.

- docs/new-version-branch.md
> [2.19] [PR 58] update of the new version branch documentation

- docs/new-version-branch.md
> [2.18] [PR 58] update of the new version branch documentation

- package.json
> [2.20] [PR 63] adding a build command for staging

- package.json
> [2.19] [PR 63] adding a build command for staging

- package.json
> [2.18] [PR 63] adding a build command for staging

- site.yml
> [2.20] [PR 67] Harmonize site.yml to be inline with docs

- site.yml
> [2.19] [PR 67] Harmonize site.yml to be inline with docs

- site.yml
> [2.18] [PR 67] Harmonize site.yml to be inline with docs

- site.yml
> [2.20] [PR 71] Add start_page in site.yml

- site.yml
> [2.19] [PR 71] Add start_page in site.yml

- site.yml
> [2.18] [PR 71] Add start_page in site.yml

- modules/ROOT/pages/accounts.adoc
- modules/ROOT/pages/appendices/troubleshooting.adoc
- modules/ROOT/pages/connecting.adoc
- modules/ROOT/pages/document_provider.adoc
- modules/ROOT/pages/faq.adoc
- modules/ROOT/pages/index.adoc
- modules/ROOT/pages/installation.adoc
- modules/ROOT/pages/settings.adoc
> [2.20] [PR 75] Setting the description attribute

- modules/ROOT/pages/accounts.adoc
- modules/ROOT/pages/appendices/troubleshooting.adoc
- modules/ROOT/pages/connecting.adoc
- modules/ROOT/pages/document_provider.adoc
- modules/ROOT/pages/faq.adoc
- modules/ROOT/pages/index.adoc
- modules/ROOT/pages/installation.adoc
- modules/ROOT/pages/settings.adoc
> [2.19] [PR 75] Setting the description attribute

- modules/ROOT/pages/index.adoc
Small fix adding a description after it has been declared.
Backport to 2.20 and 2.19
> description fix

- modules/ROOT/pages/index.adoc
> [2.20] [PR 78] description fix

- modules/ROOT/pages/index.adoc
> [2.19] [PR 78] description fix

- docs/new-version-branch.md
> [2.19] [PR 82] branching text fix

- docs/new-version-branch.md
> [2.20] [PR 82] branching text fix

- modules/ROOT/pages/installation.adoc
> fix: fix deprecated urls

- modules/ROOT/pages/installation.adoc
> [2.21] [PR 87] fix: fix deprecated urls

- modules/ROOT/pages/installation.adoc
> [2.20] [PR 87] fix: fix deprecated urls

- modules/ROOT/pages/files.adoc
This PR fixes issue #105
Backports to 2.20 and 2.21
> explaining different file size displays on different systems

- docs/new-version-branch.md
> Update the new version branch text

- site.yml
> [4.0] [PR 132] Update site.yml

- site.yml
> [3.0] [PR 132] Update site.yml

- modules/ROOT/pages/appendices/troubleshooting.adoc
> [4.1] [PR 136] Explain HTTP logging basic in troubleshooting.adoc

- .gitignore
- README.md
- bin/prepare_site_yml
> [4.1] [PR 143] Update readme and prepare dev env

- .gitignore
- README.md
- bin/prepare_site_yml
> [4.0]  [PR 143] Update readme and prepare dev env

- package.json
> [4.1] [PR 146] Update package.json

- modules/ROOT/pages/appendices/troubleshooting.adoc
(now lists HTTP logging)
---
Can be back ported to all versions.
> Improve Troubleshooting TOC

- modules/ROOT/pages/appendices/troubleshooting.adoc
> [4.1] [PR 149] Improve Troubleshooting TOC

- modules/ROOT/pages/appendices/troubleshooting.adoc
> [4.0] [PR 149] Improve Troubleshooting TOC

- docs/new-version-branch.md
> [4.0] [PR 160] Just a small internal link fix

- docs/new-version-branch.md
> [4.1] [PR 160] Just a small internal link fix

- es-docker-compose.yml
> [4.1] [PR 163] Add ES example yml for ease of testing

- es-docker-compose.yml
> [4.0] [PR 163] Add ES example yml for ease of testing

- ext-antora/generate-index.js
> [4.1] [PR 166] Fix search index generation

- ext-antora/generate-index.js
> [4.0] [PR 166] Fix search index generation

- docs/new-version-branch.md
- ext-antora/generate-index.js
- site.yml
Script update for consistency + small fixes.
Backport to 4.2 and 4.1
> ES index update

- docs/new-version-branch.md
- ext-antora/generate-index.js
- site.yml
> [4.2] [PR 170] ES index update

- docs/new-version-branch.md
- ext-antora/generate-index.js
- site.yml
> [4.1] [PR 170] ES index update

- modules/ROOT/pages/appendices/release_notes.adoc
- modules/ROOT/partials/nav.adoc
> [4.1] [PR 175] Remove the release notes page

- modules/ROOT/pages/appendices/release_notes.adoc
- modules/ROOT/partials/nav.adoc
> [4.2] [PR 175] Remove the release notes page

- .drone.star
> [4.2] [PR 178] chore: report CI result to builds channel

- package.json
- yarn.lock
> [4.3] [PR 190] Antora package.json refactoring

- .drone.star
The 4.4 branch has been created, this PR does the changes necessary for local building.
> Changes necessary for Android 4.4

- yarn.lock
> chore: recreate yarn.lock with latest package versions

- ext-antora/comp-version.js
> [4.4] [PR 202] Update antora extension to print component, versions and files

- ext-antora/comp-version.js
> [4.3] [PR 202] Update antora extension to print component, versions and files

- ext-antora/comp-version.js
> [4.4] [PR 207] Update the component-version counting extension

- docs/new-version-branch.md
- docs/the-branching-workflow.md
> [4.4] [PR 210] Update the versioning process

- docs/new-version-branch.md
- docs/the-branching-workflow.md
> [4.3] [PR 210] Update the versioning process

- .drone.star
These are the changes necessary to finalize the creation of the 4.5 branch.
* The x.y branch is already pushed, prepared and is included in the branch protection rules.
* Note that this PR can be merged at any time but:
* must be merged **before** applying content changes and
* **before** merging the docs PR to include this version.
* Post merging this, we need to backport all relevant changes created in master to 4.5
@mmattel @phil-davis
> Changes necessary for 4.5

- modules/ROOT/pages/installation.adoc
> [4.4] [PR 219] Fix image rendering
